name: Build Maven Project

on:
  push:
    branches:
      - main  # (a) desencadeia o workflow sempre que há push na branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # (b) Configurar o Java (versão 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # (c) Compilar o projeto com Maven
      - name: Build with Maven
        run: mvn clean package -B

      # (d) Publicar o ficheiro JAR gerado como artefacto
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            target/*.jar
